export default {
  CREATE_ACCOUNT: 'Create your account',
  APP_START_NAME: 'Day',
  APP_END_NAME: 'Task',
  NAME_PLACEHOLDER: 'Enter your full name',
  EMAIL_PLACEHOLDER: 'Enter your email address',
  PASSWORD_PLACEHOLDER: 'Enter your password',
  EMAIL_ICON: 'email',
  ACCOUNT_ICON: 'account',
  PASSWORD_ICON: 'shield-lock',
  FULL_NAME: 'Full Name',
  EMAIL: 'Email Address',
  PASSWORD: 'Password',
  ALREADY_ACCOUNT: 'Already have an account?',
  ALREADY_ACCOUNT_LOGIN: 'Log In',
  NAME_REQUIRED: 'Name is required',
  EMAIL_VALIDATION: 'please enter a valid email address',
  EMAIL_REQUIRED: 'Email is required',
  PASSWORD_MIN_LENGTH: 'Password must be at least 6 characters',
  PASSWORD_REQUIRED: 'Password is required',
  WELCOME_BACK: 'Welcome Back!',
  ALREADY_ACCOUNT_SIGNUP: 'Sign Up',
  MY_TASKS: 'My Tasks',
  COMPLETED: 'Completed',
  IN_PROGRESS: 'In Progress',
  CALENDAR: 'Calendar',
  TASK_NAME: 'Enter your task name',
  ENTER_TASK_DESCRIPTION: 'Enter your task description',
  ENTER_TASK_HEADING: 'Enter your one linear task detail',
  ENTER_CATEGORY_NAME: 'Enter your category',
  TASK_NAME_REQUIRED: 'Task name is required',
  DESCRIPTION_REQUIRED: 'Description is required',
  TASK_HEADING_REQUIRED: 'Task heading is required',
  CATEGORY_REQUIRED: 'Category is required',
  TASK_ICON: 'calendar-collapse-horizontal',
};
